### ISSUE TITLE
feature : 히어로 애니메이션 구현

### ISSUE THREAD

**Issue by hyunjuntyler** [BostonGosari/Baseline#1]
## ✏️ Summary

- 큰 카드 클릭시 나타나는 히어로 애니메이션을 구현합니다.
- 상세 애니메이션은 Apple 의 AppStore 을 참고하였습니다. (스크린샷 첨부)

<br>

## ✨ Description

- 히어로 애니메이션의 예시는 아래와 같습니다.

|기능|스크린샷|
|:--:|:--:|
|히어로 애니메이션|<img src = "https://github.com/BostonGosari/Baseline/assets/120548537/a3b62184-1ce4-46d6-ac1f-0e05460377d9" width ="200">|

- 클릭시 카드가 커지면서 자연스럽게 창으로 연결됩니다.
- 아래로 드래그시 창 전체가 작아지면서 첫 화면으로 되돌아 갑니다.
<br>

## ✓ Todo
- [x] 큰 카드뷰 구현 (Corner Radius 값이 한 곳이 다름)
- [x] 큰 카드 클릭시 히어로 애니메이션으로 창 전환 구현
- [x] 아래로 드래그 할 시 페이지 내리기 구현
