### ISSUE TITLE
feature : 경로 관련 추가 기능

### ISSUE THREAD

**Issue by hyunjuntyler** [BostonGosari/Baseline#18]
## ✏️ Summary
- 경로와 유저로부터의 거리를 구합니다.
- 경로 진행률을 구합니다.

<br>

## ✨ Description
- 유저가 경로의 근처에서 러닝을 시작할 수 있도록 경로와 유저와의 거리를 측정합니다.
- 유저가 경로를 이탈했을 시 안내문구를 위한 경로와 유저와의 거리를 측정합니다.
- 유저가 경로를 어느정도 뛰었는지에 대한 진행률을 표시합니다.

<br>

## ✓ Todo
- [ ] 경로와 유저로부터의 거리
- [ ] 경로 진행률 구하기

## 🍰 추가 디저트
- [ ] Path Overlay 관련 애니메이션
